# Migration Flow in the US in 2017-2022, excluding 2020

The dataset for this project originates from the US Census Bureau. The dataset contains the State-to-State migration flows for 5 years from 2017 to 2022. The data has some interesting information about the population reside in each state, number of people resided in different state one year ago, and number of people was abroad one year ago.

## First glance at the dataset
The dataset has 5 Excel files which format in multiple headers and comments. The number of rows and columns in each data file is the same.

## Exploring The Data
Here are some steps for exploring the data.
- Need to clean the dataset by removing all the titles and comments.
- Eliminate the MOE columns in all files.
- Set row 6 to be header and rename the column headers.
- Merge all the data files and transform to long format.

Let’s start with importing the necessary libaries, reading in the data, and  then aggregate.

In [1]:
# Import libaries
import pandas as pd
import numpy as np
import math
import glob
import re
import os

In [2]:
# Import all migration data
path = r'C:/Users/Nguyen/OneDrive/Desktop/migration-project/raw data/'
all_files = glob.glob(path + '/*.xlsx')

li = []

for filename in all_files:
    df = pd.read_excel(filename,na_values=['(NA)'], header = 6).fillna(0)
    
    # Remove all the MOE columns and the Footnotes which are from row 70 to 76 for all the data files
    df = df.loc[:70,(df != 'MOE').all()]

    # Adjust the column names
    df.rename(columns=
              {df.columns[0]: 'destination_state',
               df.columns[1]: 'population',
               df.columns[2]: 'same_house',
               df.columns[3]: 'same_state',
               df.columns[4]: 'from_different_state_Total',
               df.columns[-4]: 'abroad_Total',
               df.columns[-3]: 'abroad_PuertoRico',
               df.columns[-2]: 'abroad_USIslandArea',
               df.columns[-1]: 'abroad_ForeignCountry'
              }, inplace = True)

    #for i in range(4,56):
    #    df.rename(columns = {df.columns[i]:'from_state_' + df.columns[i]}, inplace = True)

    # Remove NA rows and duplicate columns
    df = df[df['destination_state'] != 0]
    df = df[df.columns.drop(list(df.filter(regex='Unnamed:')))]
    df = df.drop([2])
    df = df.drop([37])

    # Rename the first element and set the first column as index
    # df.values[0][0] = 'United States'
    
    # Change all columns to integer
    for col in df.columns[1:]:
        df[col] = df[col].astype('int64')
        
    # Create a column to store the year based on the Excel file name
    df['year'] = re.findall('\d+', os.path.basename(filename))[0]
    
    # Reset index
    df.reset_index(drop = True, inplace = True)
        
    li.append(df)

# Check out the first 5 rows of one of the files
li[0].head()

,destination_state,population,same_house,same_state,from_different_state_Total,Alabama,Alaska,Arizona,Arkansas,California,...,Virginia,Washington,West Virginia,Wisconsin,Wyoming,abroad_Total,abroad_PuertoRico,abroad_USIslandArea,abroad_ForeignCountry,year
0,Alabama,4819343,4158224,535649,111803,0,424,1513,517,2328,...,4277,1289,1070,1121,104,13667,476,0,13191,2017
1,Alaska,730874,595804,98168,30199,942,0,1387,203,3556,...,360,3653,0,2500,6,6703,0,965,5738,2017
2,Arizona,6935358,5717189,911120,261727,1337,2255,0,1763,59233,...,3593,14392,318,3897,997,45322,438,91,44793,2017
3,Arkansas,2968395,2509717,370309,79411,574,241,1060,0,5334,...,1087,1539,0,958,12,8958,573,0,8385,2017
4,California,39085984,34009331,4234770,523131,3715,2606,26907,3471,0,...,21162,33143,789,9348,1395,318752,1864,842,316046,2017

In [3]:
li[4].head()

,destination_state,population,same_house,same_state,from_different_state_Total,Alabama,Alaska,Arizona,Arkansas,California,...,Virginia,Washington,West Virginia,Wisconsin,Wyoming,abroad_Total,abroad_PuertoRico,abroad_USIslandArea,abroad_ForeignCountry,year
0,Alabama,5022366,4397470,471530,139263,0,714,1202,1536,8012,...,3654,1639,268,203,0,14103,311,611,13181,2022
1,Alaska,724196,614091,68351,36563,151,0,1645,10,3855,...,345,3076,0,943,42,5191,129,265,4797,2022
2,Arizona,7285247,6264863,690856,282729,727,2091,0,1147,74157,...,3791,21242,471,6569,1863,46799,608,840,45351,2022
3,Arkansas,3007872,2618120,294640,86375,1911,64,1776,0,7783,...,978,2703,43,481,326,8737,18,0,8719,2022
4,California,38629179,34335186,3515077,475803,5204,2040,27412,963,0,...,15373,31866,42,4407,1083,303113,1804,3158,298151,2022

In [85]:
li[0].head(25)

,destination_state,population,same_house,same_state,from_different_state_Total,Alabama,Alaska,Arizona,Arkansas,California,...,Virginia,Washington,West Virginia,Wisconsin,Wyoming,abroad_Total,abroad_PuertoRico,abroad_USIslandArea,abroad_ForeignCountry,year
0,Alabama,4819343,4158224,535649,111803,0,424,1513,517,2328,...,4277,1289,1070,1121,104,13667,476,0,13191,2017
1,Alaska,730874,595804,98168,30199,942,0,1387,203,3556,...,360,3653,0,2500,6,6703,0,965,5738,2017
2,Arizona,6935358,5717189,911120,261727,1337,2255,0,1763,59233,...,3593,14392,318,3897,997,45322,438,91,44793,2017
3,Arkansas,2968395,2509717,370309,79411,574,241,1060,0,5334,...,1087,1539,0,958,12,8958,573,0,8385,2017
4,California,39085984,34009331,4234770,523131,3715,2606,26907,3471,0,...,21162,33143,789,9348,1395,318752,1864,842,316046,2017
5,Colorado,5542282,4546729,734182,226933,3120,2030,6765,1356,27014,...,6099,6675,42,3506,5135,34438,828,568,33042,2017
6,Connecticut,3556297,3136666,311726,83325,206,540,644,160,2807,...,1314,374,0,188,257,24580,3780,0,20800,2017
7,Delaware,952449,830905,78998,38532,506,0,76,0,580,...,1510,0,371,296,0,4014,260,66,3688,2017
8,District of Columbia,684810,554225,64013,56231,494,0,549,105,3763,...,7509,206,0,115,0,10341,356,78,9907,2017
9,Florida,20772371,17554348,2402381,566476,9389,1400,5577,3028,30919,...,28232,6176,2187,7202,396,249166,28538,2847,217781,2017
10,Georgia,10299497,8760762,1202587,278889,15270,986,6218,2055,12052,...,11256,2649,420,3504,630,57259,3345,306,53608,2017
11,Hawaii,1410750,1231340,115683,46457,844,424,1666,48,8843,...,2656,2837,0,213,96,17270,11,1572,15687,2017
12,Idaho,1694182,1405344,210310,71899,58,796,1523,265,21372,...,612,8881,0,442,1747,6629,67,0,6562,2017
13,Illinois,12659328,11026895,1365922,195092,1682,270,4159,2591,16046,...,4127,4846,130,12274,414,71419,1829,0,69590,2017
14,Indiana,6591598,5633171,792487,142290,1216,131,948,852,10096,...,1867,2782,1044,3757,0,23650,144,93,23413,2017
15,Iowa,3106880,2654666,362905,77072,817,629,2346,693,2625,...,774,1405,550,3011,54,12237,67,0,12170,2017
16,Kansas,2876925,2413141,366147,86154,276,515,1404,1225,6511,...,1029,801,0,317,123,11483,347,0,11136,2017
17,Kentucky,4404279,3721100,563721,103985,2851,506,333,342,4466,...,2453,1428,2140,1599,266,15473,1402,0,14071,2017
18,Louisiana,4629962,4030674,513676,72836,2830,199,520,3289,5534,...,2073,623,261,319,195,12776,455,0,12321,2017
19,Maine,1322591,1140136,144186,34252,246,163,322,12,1578,...,1162,336,72,0,0,4017,12,0,4005,2017
20,Maryland,5988007,5168350,605885,165654,644,961,1689,410,8994,...,23315,1839,3926,901,44,48118,1808,488,45822,2017
21,Massachusetts,6789798,5888011,677835,146299,212,539,1030,207,12745,...,3083,1672,161,1098,0,77653,6748,273,70632,2017
22,Michigan,9851330,8450559,1203536,148787,3669,348,4948,825,10874,...,3539,1572,392,3485,635,48448,2621,29,45798,2017
23,Minnesota,5510902,4728748,643272,115623,491,671,2587,634,5518,...,1552,3333,44,20555,213,23259,503,0,22756,2017
24,Mississippi,2946971,2553271,313673,73549,5936,127,553,2251,4709,...,286,888,1158,402,212,6478,281,31,6166,2017

In [74]:
all_files

['C:/Users/Nguyen/OneDrive/Desktop/migration-project/raw data\\State_to_State_Migrations_Table_2017.xlsx',
 'C:/Users/Nguyen/OneDrive/Desktop/migration-project/raw data\\State_to_State_Migrations_Table_2018.xlsx',
 'C:/Users/Nguyen/OneDrive/Desktop/migration-project/raw data\\State_to_State_Migrations_Table_2019.xlsx',
 'C:/Users/Nguyen/OneDrive/Desktop/migration-project/raw data\\State_to_State_Migrations_Table_2021.xlsx',
 'C:/Users/Nguyen/OneDrive/Desktop/migration-project/raw data\\State_to_State_Migrations_Table_2022.xlsx']

Concatenate all dataframes.

In [87]:
migration_df = pd.concat(li)
migration_df.head(56)

,destination_state,population,same_house,same_state,from_different_state_Total,Alabama,Alaska,Arizona,Arkansas,California,...,Virginia,Washington,West Virginia,Wisconsin,Wyoming,abroad_Total,abroad_PuertoRico,abroad_USIslandArea,abroad_ForeignCountry,year
0,Alabama,4819343,4158224,535649,111803,0,424,1513,517,2328,...,4277,1289,1070,1121,104,13667,476,0,13191,2017
1,Alaska,730874,595804,98168,30199,942,0,1387,203,3556,...,360,3653,0,2500,6,6703,0,965,5738,2017
2,Arizona,6935358,5717189,911120,261727,1337,2255,0,1763,59233,...,3593,14392,318,3897,997,45322,438,91,44793,2017
3,Arkansas,2968395,2509717,370309,79411,574,241,1060,0,5334,...,1087,1539,0,958,12,8958,573,0,8385,2017
4,California,39085984,34009331,4234770,523131,3715,2606,26907,3471,0,...,21162,33143,789,9348,1395,318752,1864,842,316046,2017
5,Colorado,5542282,4546729,734182,226933,3120,2030,6765,1356,27014,...,6099,6675,42,3506,5135,34438,828,568,33042,2017
6,Connecticut,3556297,3136666,311726,83325,206,540,644,160,2807,...,1314,374,0,188,257,24580,3780,0,20800,2017
7,Delaware,952449,830905,78998,38532,506,0,76,0,580,...,1510,0,371,296,0,4014,260,66,3688,2017
8,District of Columbia,684810,554225,64013,56231,494,0,549,105,3763,...,7509,206,0,115,0,10341,356,78,9907,2017
9,Florida,20772371,17554348,2402381,566476,9389,1400,5577,3028,30919,...,28232,6176,2187,7202,396,249166,28538,2847,217781,2017
10,Georgia,10299497,8760762,1202587,278889,15270,986,6218,2055,12052,...,11256,2649,420,3504,630,57259,3345,306,53608,2017
11,Hawaii,1410750,1231340,115683,46457,844,424,1666,48,8843,...,2656,2837,0,213,96,17270,11,1572,15687,2017
12,Idaho,1694182,1405344,210310,71899,58,796,1523,265,21372,...,612,8881,0,442,1747,6629,67,0,6562,2017
13,Illinois,12659328,11026895,1365922,195092,1682,270,4159,2591,16046,...,4127,4846,130,12274,414,71419,1829,0,69590,2017
14,Indiana,6591598,5633171,792487,142290,1216,131,948,852,10096,...,1867,2782,1044,3757,0,23650,144,93,23413,2017
15,Iowa,3106880,2654666,362905,77072,817,629,2346,693,2625,...,774,1405,550,3011,54,12237,67,0,12170,2017
16,Kansas,2876925,2413141,366147,86154,276,515,1404,1225,6511,...,1029,801,0,317,123,11483,347,0,11136,2017
17,Kentucky,4404279,3721100,563721,103985,2851,506,333,342,4466,...,2453,1428,2140,1599,266,15473,1402,0,14071,2017
18,Louisiana,4629962,4030674,513676,72836,2830,199,520,3289,5534,...,2073,623,261,319,195,12776,455,0,12321,2017
19,Maine,1322591,1140136,144186,34252,246,163,322,12,1578,...,1162,336,72,0,0,4017,12,0,4005,2017
20,Maryland,5988007,5168350,605885,165654,644,961,1689,410,8994,...,23315,1839,3926,901,44,48118,1808,488,45822,2017
21,Massachusetts,6789798,5888011,677835,146299,212,539,1030,207,12745,...,3083,1672,161,1098,0,77653,6748,273,70632,2017
22,Michigan,9851330,8450559,1203536,148787,3669,348,4948,825,10874,...,3539,1572,392,3485,635,48448,2621,29,45798,2017
23,Minnesota,5510902,4728748,643272,115623,491,671,2587,634,5518,...,1552,3333,44,20555,213,23259,503,0,22756,2017
24,Mississippi,2946971,2553271,313673,73549,5936,127,553,2251,4709,...,286,888,1158,402,212,6478,281,31,6166,2017
25,Missouri,6039877,5108238,742205,164957,2518,1224,2820,6560,10918,...,2795,3120,90,3784,529,24477,943,180,23354,2017
26,Montana,1039170,883342,116400,35456,301,701,386,899,5447,...,683,3879,112,497,4072,3972,151,0,3821,2017
27,Nebraska,1894217,1586729,243792,52507,420,199,1456,267,3707,...,774,351,164,694,572,11189,436,115,10638,2017
28,Nevada,2963456,2430163,383067,133074,191,1024,5508,551,47513,...,1147,5203,0,381,143,17152,384,783,15985,2017
29,New Hampshire,1330742,1134244,137212,52893,109,151,190,185,2418,...,460,146,0,97,0,6393,547,90,5756,2017
30,New Jersey,8910191,7968039,710807,152106,169,610,898,175,7968,...,5750,1135,329,1013,110,79239,4195,73,74971,2017
31,New Mexico,2062628,1801560,193225,57255,770,1470,7129,258,6897,...,1694,563,0,274,267,10588,131,0,10457,2017
32,New York,19638923,17553033,1655152,285252,1849,1049,3826,1209,24982,...,10677,5529,402,1269,54,145486,5910,1325,138251,2017
33,North Carolina,10158556,8649400,1139260,313834,4526,1401,5624,747,22469,...,27833,5896,3423,1895,159,56062,3011,385,52666,2017
34,North Dakota,744641,609017,92436,37315,53,152,564,48,4051,...,434,1362,0,861,829,5873,664,0,5209,2017
35,Ohio,11520109,9822847,1452745,198929,2487,79,3143,683,11286,...,5224,2960,7343,2011,248,45588,3765,267,41556,2017
36,Oklahoma,3875922,3216306,542724,101961,1133,1004,1931,6835,7174,...,921,2018,0,509,251,14931,386,96,14449,2017
37,Oregon,4102048,3405784,520747,149513,179,2808,6938,526,50109,...,3566,26150,257,1370,227,26004,0,220,25784,2017
38,Pennsylvania,12674642,11072942,1292389,250120,1416,294,3266,292,10995,...,8417,3199,4128,1696,0,59191,7783,378,51030,2017
39,Rhode Island,1048549,922210,83440,36850,135,109,101,175,2418,...,1643,1215,0,233,0,6049,306,0,5743,2017
40,South Carolina,4966211,4248517,531315,166573,2133,0,2380,232,7618,...,8778,1420,3111,1627,0,19806,1506,197,18103,2017
41,South Dakota,856726,723740,99781,26106,144,183,402,83,3599,...,364,195,0,974,728,7099,358,58,6683,2017
42,Tennessee,6642072,5675990,748912,191909,9523,417,2522,5843,7879,...,11339,1789,996,1426,362,25261,979,773,23509,2017
43,Texas,27924632,23534387,3643333,524511,10235,3543,14875,14222,63174,...,15436,14646,1353,7443,948,222401,5105,1714,215582,2017
44,Utah,3056193,2532858,398606,99584,644,660,8144,177,17020,...,3187,5270,142,1064,1722,25145,0,502,24643,2017
45,Vermont,619089,536390,57588,21868,0,203,132,0,1246,...,636,181,48,106,643,3243,125,0,3118,2017
46,Virginia,8372522,7089782,958267,250490,2341,736,2587,1184,14509,...,0,5488,5294,961,305,73983,1318,850,71815,2017
47,Washington,7318811,6016482,978057,260787,1605,7532,11733,1074,52484,...,7976,0,547,2106,581,63485,88,1992,61405,2017
48,West Virginia,1798306,1589833,165375,40007,239,121,13,0,563,...,5388,469,0,173,0,3091,103,0,2988,2017
49,Wisconsin,5731549,4908638,687285,112519,757,389,1702,601,4741,...,1671,2531,507,0,273,23107,2541,74,20492,2017
50,Wyoming,573483,481231,71338,18511,264,152,220,722,2344,...,843,759,0,20,0,2403,0,0,2403,2017
51,Puerto Rico,3313519,3101332,189034,20167,888,5,108,0,1567,...,541,0,0,0,0,2986,0,97,2889,2017
0,Alabama,4832358,4173026,534914,109301,0,419,1915,1051,2659,...,5221,2125,176,996,74,15117,957,893,13267,2018
1,Alaska,727164,608707,81229,32099,518,0,910,722,3455,...,654,2558,0,340,192,5129,344,267,4518,2018
2,Arizona,7090137,5887700,888452,273714,2801,2743,0,1487,68516,...,4956,17560,29,7788,929,40271,1289,1449,37533,2018
3,Arkansas,2975961,2539294,354774,73179,438,413,602,0,3728,...,900,1328,72,130,0,8714,1693,0,7021,2018

Transform to long format.

In [88]:
id_var = ['destination_state','year', 'population','same_house', 'same_state','from_different_state_Total','abroad_Total']
id_values = [col for col in migration_df.columns if col not in id_var]
df_long = pd.melt( migration_df, id_var , id_values, 'from', 'number_of_people' )
df_long.head(53)

,destination_state,year,population,same_house,same_state,from_different_state_Total,abroad_Total,from,number_of_people
0,Alabama,2017,4819343,4158224,535649,111803,13667,Alabama,0
1,Alaska,2017,730874,595804,98168,30199,6703,Alabama,942
2,Arizona,2017,6935358,5717189,911120,261727,45322,Alabama,1337
3,Arkansas,2017,2968395,2509717,370309,79411,8958,Alabama,574
4,California,2017,39085984,34009331,4234770,523131,318752,Alabama,3715
5,Colorado,2017,5542282,4546729,734182,226933,34438,Alabama,3120
6,Connecticut,2017,3556297,3136666,311726,83325,24580,Alabama,206
7,Delaware,2017,952449,830905,78998,38532,4014,Alabama,506
8,District of Columbia,2017,684810,554225,64013,56231,10341,Alabama,494
9,Florida,2017,20772371,17554348,2402381,566476,249166,Alabama,9389
10,Georgia,2017,10299497,8760762,1202587,278889,57259,Alabama,15270
11,Hawaii,2017,1410750,1231340,115683,46457,17270,Alabama,844
12,Idaho,2017,1694182,1405344,210310,71899,6629,Alabama,58
13,Illinois,2017,12659328,11026895,1365922,195092,71419,Alabama,1682
14,Indiana,2017,6591598,5633171,792487,142290,23650,Alabama,1216
15,Iowa,2017,3106880,2654666,362905,77072,12237,Alabama,817
16,Kansas,2017,2876925,2413141,366147,86154,11483,Alabama,276
17,Kentucky,2017,4404279,3721100,563721,103985,15473,Alabama,2851
18,Louisiana,2017,4629962,4030674,513676,72836,12776,Alabama,2830
19,Maine,2017,1322591,1140136,144186,34252,4017,Alabama,246
20,Maryland,2017,5988007,5168350,605885,165654,48118,Alabama,644
21,Massachusetts,2017,6789798,5888011,677835,146299,77653,Alabama,212
22,Michigan,2017,9851330,8450559,1203536,148787,48448,Alabama,3669
23,Minnesota,2017,5510902,4728748,643272,115623,23259,Alabama,491
24,Mississippi,2017,2946971,2553271,313673,73549,6478,Alabama,5936
25,Missouri,2017,6039877,5108238,742205,164957,24477,Alabama,2518
26,Montana,2017,1039170,883342,116400,35456,3972,Alabama,301
27,Nebraska,2017,1894217,1586729,243792,52507,11189,Alabama,420
28,Nevada,2017,2963456,2430163,383067,133074,17152,Alabama,191
29,New Hampshire,2017,1330742,1134244,137212,52893,6393,Alabama,109
30,New Jersey,2017,8910191,7968039,710807,152106,79239,Alabama,169
31,New Mexico,2017,2062628,1801560,193225,57255,10588,Alabama,770
32,New York,2017,19638923,17553033,1655152,285252,145486,Alabama,1849
33,North Carolina,2017,10158556,8649400,1139260,313834,56062,Alabama,4526
34,North Dakota,2017,744641,609017,92436,37315,5873,Alabama,53
35,Ohio,2017,11520109,9822847,1452745,198929,45588,Alabama,2487
36,Oklahoma,2017,3875922,3216306,542724,101961,14931,Alabama,1133
37,Oregon,2017,4102048,3405784,520747,149513,26004,Alabama,179
38,Pennsylvania,2017,12674642,11072942,1292389,250120,59191,Alabama,1416
39,Rhode Island,2017,1048549,922210,83440,36850,6049,Alabama,135
40,South Carolina,2017,4966211,4248517,531315,166573,19806,Alabama,2133
41,South Dakota,2017,856726,723740,99781,26106,7099,Alabama,144
42,Tennessee,2017,6642072,5675990,748912,191909,25261,Alabama,9523
43,Texas,2017,27924632,23534387,3643333,524511,222401,Alabama,10235
44,Utah,2017,3056193,2532858,398606,99584,25145,Alabama,644
45,Vermont,2017,619089,536390,57588,21868,3243,Alabama,0
46,Virginia,2017,8372522,7089782,958267,250490,73983,Alabama,2341
47,Washington,2017,7318811,6016482,978057,260787,63485,Alabama,1605
48,West Virginia,2017,1798306,1589833,165375,40007,3091,Alabama,239
49,Wisconsin,2017,5731549,4908638,687285,112519,23107,Alabama,757
50,Wyoming,2017,573483,481231,71338,18511,2403,Alabama,264
51,Puerto Rico,2017,3313519,3101332,189034,20167,2986,Alabama,888
52,Alabama,2018,4832358,4173026,534914,109301,15117,Alabama,0

Export to CSV file and use this data to make Dashboard.

In [77]:
df_long.to_csv('migration_5years.csv', index=False)